version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: carspare-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:    
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carspare_network

  adminer:
    image: adminer
    container_name: carspare-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db  # Connects to "db" service
    ports:
      - "8080:8080"
    networks:
      - carspare_network

volumes:
  postgres_data:

networks:
  carspare_network:
