"""added enum for spare parts category

Revision ID: 6ff112135e4e
Revises: f30c5b314918
Create Date: 2025-04-16 12:51:22.359435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ff112135e4e'
down_revision: Union[str, None] = 'f30c5b314918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spare_parts', 'category',
               existing_type=postgresql.ENUM('interior', 'exterior', 'other', name='part_category'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spare_parts', 'category',
               existing_type=postgresql.ENUM('interior', 'exterior', 'other', name='part_category'),
               nullable=False)
    # ### end Alembic commands ###
